### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by csweet89** [Caesius-Leo/Deadly_Deadly_Dungeon_Feedback#3] opened 2024-12-04 21:49 UTC
First off, love this datapack. Its a real shame more people dont use it. The dungeons are crafted well and there is a lot of variety in rooms and layout. I especially like how the interior changes as you go deeper. 

I wanted to request that the modified Trial Vaults for bosses would eventually "cooldown" and allow folks to re-open them.
As it stands, you can only open them once per vault, per player.

They are super powerful, so a 30 min cooldown like vanilla trial chambers is probably too fast. Perhaps 24 hours? or even a few days?

Not sure if this is possible, thanks!

**Comment by Caesius-Leo** [comment] 2024-12-04 23:50
Hi there, nice to meet you! I'm glad that you like the datapack :) 
I think that your second request is a good idea and i will add more time in the 1.21.4 update (Mojang changed a lot of technical stuff and i will need some time to update everything).  
I don't really like the first one. On a technical level is somewhat doable but it will probably lag the game a lot, on the concept side i don't like it so much. Vault are supposed to replace chests so other players can have a reward for killing the boss, like in vanilla minecraft for the trial chambers. 
There is a lot of discussion on this topic also, so i will stick for the vanilla design for now, but if you want there is another datapack that should work fine with DDD : https://modrinth.com/datapack/renewable-vaults
The only thing is that is not updated, so you need to ask the author for an update or find a new one that will work.

Have a great day :)

**Comment by csweet89** [comment] 2024-12-05 00:31
Wow! Speedy reply!
Quick clarification, what do you mean by 1st and 2nd request? 
I only have one request, technically... just allow vaults to be re-opened by the same player eventually.

So long as the cooldown isnt like over a month or something, i think itd be fine.

If you want to stick to "one and done" thats fine too though. 

Thanks again!

**Comment by Caesius-Leo** [comment] 2024-12-05 10:45
Oh, i understood that you requested the reusability (first) and a longer cooldown.
Let's do this: i will extend the cooldown to something like 4h and i will try to make a separate add-on that you can use together with DDD to make the vault reusable.
If i will be able to make something decent, I will put the link the changelog of 1.21.4 update. Just be patient because time is something that i'm lacking these months.

Have a great time in the dungeons :)

Caesius Leo

**Comment by csweet89** [comment] 2024-12-05 22:34
Is there currently any kind of cooldown? Currently, if myself and a friend clear a dungeon together for the first time, _**I think**_ we can both use our individual keys back to back...?
If so, I think this is good since each reward is for each person.

The cooldown is only relevant IF we allow people to re-use the same dungeon vault.

No rush at all on adding or making this update! The server I play on is on 1.21.3 and will be there for awhile I think.

Here's a thought... Perhaps add a toggle setting into the mod so that there is a config file that is created where you can say "allow players to reopen vaults = true|false" and optionally also "hours to reopen vaults=#"?
I know a mod can have a config file... I think a datapack can be affected by server commands? Or perhaps it can RUN a command, but you cant edit the configs bc they are stored within the datapack. 
In which case, it could be a setting bundled into the "\data\ddd\function" folder as a function that people can edit manually if they want?


Complete side note bc I'm kind of dumb with datapacks
I play on a server that uses the "mod" version of DDD. They do not use the datapack. I dont have the mod locally installed so I dont see the custom textures.
1. Do they ALSO need to install the datapack? Or is it one or the other?
2. If they ONLY used the datapack, would everyone automatically download it and see the custom textures?
3. If we switch from Mod to Datapack, would it break things?
Sorry for the tangent... I'm just realizing theres a lot to learn since I last focused on minecraft modding back in 2018

**Comment by csweet89** [comment] 2024-12-06 01:51
Yes, instant claims for different players works.
We discovered the diff keys and its very cool.

Cool idea about functions, but also within a function someone can edit a line to FALSE or something. That works too.

Right now, the vanilla trial chamber vaults DO refill/respawn.
The modded ones you made do not. I dont know why. I thought that was intentional functionality.

I installed the mod locally since the server uses the mod. Perhaps they can switch to datapack in the future. For now, the textures work for me. (as a personal side note, while your texture designs are cool, I do think id perfer if they were less high-res, to match the minecraft art style but i DO like the design choices.)

**Comment by Caesius-Leo** [comment] 2024-12-06 21:45
Sorry yesterday i was tired and i confused the vault with the trial spawners. Only trial spawners can have a cooldown, vaults can be opened only one time for a specific player also in vanilla.
Idk if you are using any mods that change their behaviour, but in vanilla VAULTS can't refill ( https://minecraft.wiki/w/Vault#:~:text=Each%20vault%20keeps%20track%20of,to%20open%20the%20vault%20again. )
I will extend the cooldown for the SPAWNERS, and add the functions to refill the VAULTS, at the end of the day you will need keys to open the vaults so it's the same.
I will check for any unexpected behaviour in the update and if something is broken i will fix it
I will let this issue open and i will write when the update will be done

P.S.
Thank you for the texture feedback , i'm happy that you liked the design, for the resolution you have  a point, i will make my considerations about that

See you soon :)

**Comment by csweet89** [comment] 2024-12-06 22:43
Ahh, i also confuse myself with Trial spawners vs vaults. I know the difference, but i possibly messed up my wording in my posts.

I think the SPAWNER cooldown might be fine as is? I kind of like using them for a fun fight to test gear. haha
Though, the other dungeon spawners are fine for that as well.

Ok, I DEFINITELY misunderstood vaults in vanilla. I watch a lot of YouTube tutorials and I was confused about Trial Chamber farms and thought they were farming vaults as well as mobs for the materials. Looks like they JUST farm SPAWNERS.
Completely my mistake!!!

Ok, glad I didnt offend. Its mostly a personal preference, but I think it would fit more with the vanilla minecraft aethetic if they were more pixelated. 

(Another idea I had after thinking about it... It might be cool if you did like blue eyes for the ominous keys on the knight one, or just overall added blue elements to each key, rather than 3 heads. That might be neat since the vaults are blue? Definitely just a personal idea tho, and please express your art however you best like!)

**Comment by Caesius-Leo** [comment] 2024-12-06 23:37
LOL minecraft 2024 confusion moment
Don't to worry i will find a balace for spawners
For the texure you are just expressing your opinion, i will consider it and i will try, but if i don't like the result with the 16 x16 pixels i will stay with the 32x32. Anyway, this is low priority right now
For the blue i tried and i did it for 2 or 3 keys, but after that it was too limiting so i scrapped the idea

**Comment by csweet89** [comment] 2024-12-09 22:59
I see you released a 1.21.4 version. Are any of the changes about allowing vaults to be reused included? If so, will there be a new config file for the mod where we toggle the function?

Btw, super fast turn around on mod update regardless!!

**Comment by Caesius-Leo** [comment] 2024-12-10 01:10
Hello there, sorry i'm still working on it :( . There was some slowdown in the work and I uploaded the update to 1.21.4 without it because i don't want to keep people waiting to play the latest version of minecraft.
I will write here when is ready :)

**Comment by Caesius-Leo** [comment] 2024-12-11 21:26
Here we are my friend: https://modrinth.com/datapack/deadly-deadly-dungeon/version/1.0.4.3
This is the datapack version and it's working, there are also particle during the refilling! 
For the confing in the mod version i need to study it a bit if there is a way to do it, but for now i hope you can enjoy :)

**Comment by csweet89** [comment] 2024-12-11 21:41
Awesome, i love that its done. I hate to be the bearer of bad news tho, the server owner is using the mod version rn and will be staying that way for the forseeable future. So i wont be thoroughly testing it until we have a mod version. sorry!!

**Comment by csweet89** [comment] 2024-12-15 02:22
Hey, wanted to check in to ask if there was going to be a "mod" version of the refilling mechanic in the future?

I know the datapack version exists, but we are kind of avoiding it on our server due to the concern of the long spawning time since we are running the server on weak hardware.

I am looking forward to trying it though! In single player I am enjoying it :)

**Comment by Caesius-Leo** [comment] 2024-12-15 09:35
Hello there, due to technical issues (like compatibility with different mod loaders and other stuff) and limitations of datapacks is not possible to add this config without breaking something here or there. Furthermore, a theoretical mod version will have parity problems with the datapack version.
For these and more reasons i decided to separate this feature from the main mod and to create a new one. The new mod/datapack is ready and actually under review by the modrinth staff.
When they will be ok, you will find the mod here: https://modrinth.com/datapack/oh-my-vault!
You can use this together with ddd or in vanilla as you wish
I hope this can be a good compromise :)

**Comment by csweet89** [comment] 2024-12-15 21:00
Oh wow! Thats a great idea! Now no config is necessary either. 
I really appreciate that this feature request was turned into a whole other mod. That's extremely cool and I'm really impressed!

We'll probably stick to DDD in mod version and add the new one as well :)

**Comment by Caesius-Leo** [comment] 2024-12-16 17:52
Thank you so much for the kind words! I'm really glad you liked the idea and appreciate the effort behind turning the feature request into a new mod. It means a lot to hear such positive feedback!
If there's anything I can help with or if you have further suggestions, feel free to let me know. Thanks again for your support and enthusiasm!

You can download the mod here: https://modrinth.com/datapack/oh-my-vault

I'll go ahead and close this ticket now. Wishing you all the best !

**Closed by Caesius-Leo** 2024-12-16 17:52 UTC
